### PR TITLE
Async stuck fix

### LINKED ISSUE #45: buku tidak dapat render pada local host
## Describe the bug
pada local host buku tidak dapat render ketika kita pindah tab / halaman , 
sehingga buku dapat muncul dengan reload

### PR DESCRIPTION
**Pull request by Klrfl**
- use useAsyncData to fetch data on server
should fix #45

### CODE REVIEW

**Comment by Klrfl** [comment]
Ges @Joosee24 @Adreon19 minta tolong dong dikonfirmasi kalau bugnya sudah hilang sama sekali... baru di-merge

**Comment by Adreon19** [comment]
lets go
Screenshot 2024-04-24 204541

**Review by Adreon19 — APPROVED** [review]

**Review by Adreon19 — APPROVED** [review]
great

**Review by Adreon19 — APPROVED** [review]
Screenshot 2024-03-27 153752

**Review by Adreon19 — APPROVED** [review]
Screenshot_20230212_013425

**Pull request merged**
