### PR TITLE
Feat/history

### LINKED ISSUE #75: Add history/audit feature
## Describe the feature

Keeping historical data is very important because it allows for auditing and recording what change occured when... Currently, due to how the `peminjaman` table works, every borrowing is mutated directly, losing historical data. A `peminjaman_history` table which has identical columns, and therefore is identical to `peminjaman`, can be implemented very easily.

## Implementation idea

- make a new table called `peminjaman_history`
- query historical data from that table. The data can be used to display recent activity, and display historical activity in each user's page
- make a cron job or something to delete records older than 2 years (arbitrary limit)

## Additional info

Can be implemented quickly but needs help implementing and testing...

### PR DESCRIPTION
**Pull request by Klrfl**
This breaking PR corrects history logic by
- adding a new table, 
- changing some existing columns,
- and some refactoring to reduce code

### CODE REVIEW

**Comment by Klrfl** [comment]
tasks:
- [x] order history in profil page according to borrow date ascending
- [x] document everything in version control via migration files
- [x] update trigger and function to increment and decrement `jumlah_exspl`, then remove temporary insertion in cancel function and borrow function. Also remove redundant columns (`peminjaman.tgl_kembali`)

**Comment by Adreon19** [comment]
Neco-arc

**Review by Adreon19 — COMMENTED** [review]
ITS WORKING

**Comment by Adreon19** [comment]
RobloxScreenShot20230322_005910522

**Comment by Klrfl** [comment]
Screenshot (91)

**Pull request merged**
