### PR TITLE
fixing router-link for CTA in wishlist

### PR DESCRIPTION
**Pull request by Adreon19**
you forgot to write `as="router-link"` so the CTA wont work. Hope it helps!
HD wallpaper_ Fate Series, Fate_Grand Order, Black and White, Jeanne d'Arc Alter
Screenshot 2023-04-27 004242

### CODE REVIEW

**Comment by Klrfl** [comment]
not look good what are those images

**Comment by Adreon19** [comment]
you hate it?🥺

**Comment by Klrfl** [comment]
ok sudah dites?

**Comment by Klrfl** [comment]
LGTM

**Pull request merged**
