### PR TITLE
Minor patch

### LINKED ISSUE #50: ESLint throw error saat development
## Describe the bug
ESLint ngethrow error terus pas development. Kayanya disebabkan konfigurasi plugin Vue yang ga bener deh.

## Expected behavior
Seharusnya ESLint dan plugin Vue saling integrasi dengan baik

ss

## Additional context
Hanya terjadi saat development

### PR DESCRIPTION
**Pull request by Klrfl**
- upgrade Nuxt version to fix ESlint errors
- fix PostCSS config
- pin pnpm and Node version to match cross machine local builds and deploy

### CODE REVIEW

**Comment by Klrfl** [comment]
currently failing because of ESLint latest version 9.15.0
fix is already on the way but in the mean time we wait:
- https://github.com/eslint/eslint/issues/19134
- https://github.com/typescript-eslint/typescript-eslint/issues/10338

**Review by Adreon19 — APPROVED** [review]
everything seems okay but again its still on progress for fixing the lint (wait for a couple of days)
Screenshot 2024-02-09 133645

**Comment by Adreon19** [comment]
why did you dislike my approval
Screenshot 2024-08-16 135107

**Review by Adreon19 — COMMENTED** [review]
upgrading eslint version, nice
Screenshot 2024-10-09 093801

**Comment by Adreon19** [comment]
suruh contributor di nuxt nya lebih cepet pls
skibidi-skibidi-toilet

**Pull request merged**
