### PR TITLE
Fetch

### PR DESCRIPTION
**Pull request by Klrfl**
fix data fetching problems that blocks navigation

### CODE REVIEW

**Comment by Klrfl** [comment]
todo:
- [x] handle errors in data fetching

**Comment by Klrfl** [comment]
Sudah oke di prod

**Comment by Adreon19** [comment]
mantap wak udah gk lemot lagi loading nya
Screenshot (389)

**Comment by Klrfl** [comment]
Kasian Github kehabisan disk space nyimpen gambar roblox lu

**Comment by Adreon19** [comment]
ah elah gambarnya cuma dikit kok😭😭
Screenshot (318)

**Pull request merged**
